apiVersion: v1
kind: Deployment
metadata:
  name: api-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-guide
  template:
    metadata:
      labels:
        name: api-guide
    spec:
      containers:
      - name: api-guide
        image: [docker-image-tag]
        volumeMounts:
        - mountPath: /api-guide
          name: guide-emptydir
        args:
        - sleep
        - "1800"
        resources:
          limits:
            cpu: "1"
            memory: "128Mi"
          requests:
            cpu: "0.5"
            memory: "64Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: guide-emptydir
        emptyDir:
          sizeLimit: 256Mi
