apiVersion: v1
kind: Pod
metadata:
  labels:
    run: api-guide
  name: api-guide
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
    - mountPath: /api-guide
      name: guide-emptydir
    args:
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:   
  - name: guide-emptydir
    emptyDir:
      sizeLimit: 256Mi