apiVersion: v1
kind: Service
metadata:
  name: api-guide
  labels:
    name: api-guide
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
      app: api-guide
