apiVersion: v1
kind: Service
metadata:
  name: api-guide-service
  labels:
    name: api-guide-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: api-guide
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: NodePort
