name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Docker image name
      run: echo "::set-env name=DOCKER_IMAGE_NAME::$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')"

    - name: Build Docker image
      run: docker build -t $DOCKER_IMAGE_NAME .

    - name: Push Docker image to Docker Hub
      run: docker push $DOCKER_IMAGE_NAME