name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Debug
        run: |
          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"
          echo "Docker Access Token: ${{ secrets.DOCKER_ACCESS_TOKEN }}"

      - name: Build Docker image
        run: docker build -t randeldarlei/api-guide .

      - name: Push Docker image to Docker Hub
        run: docker push randeldarlei/api-guide
