name: Deploy to Kind Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kind
        run: |
          # Configure Kind Cluster

          kind create cluster --name deploy-k8s
          kubectl cluster-info --context kind-keploy-k8s

      - name: Configure kubectl
        run: |
          CURRENT_CONTEXT=$(kubectl config current-context)
          echo "Current Kubernetes context: $CURRENT_CONTEXT"
          kubectl config use-context "$CURRENT_CONTEXT"


      - name: Deploy to Kind Cluster
        run: |
          
          kubectl apply -f kubernetes/pod.yaml -f kubernetes/service.yaml
      
      - name: Execute Python app
        run: |
          kubectl exec -it deployment/api-guide-deployment --python /python-api.py